modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="aetheria"
version="1.1"
displayName="aetheria"
credits="Created using mod maker MCreator - https://mcreator.net/about and a speccial thanks to Cube Kid for creating  this universe."
displayURL="https://mcreator.net"
authors="10ion, Pylons, Noah, Da_Dragon, Mikeadon, BadBird, Gamer, DJDARKWATERS, jointheprayerbro , KidOfCubes "
description='''
The Aetheria Mod is the mod from Cube Kid's books come to real minecraft
'''

[[dependencies.aetheria]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




