modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="aetheria"
version="1.0.0"
displayName="aetheria"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="10ion, Pylons, Noah, Da_Dragon, Mikeadon, BadBird, Gamer, DJDARKWATERS, jointheprayerbro , KidOfCubes "

[[dependencies.aetheria]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



