modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="aetheria"
version="1.1"
displayName="Aetheria"
credits="a special thanks to Cube Kid for creating  this universe."
displayURL="https://mcreator.nethttps://aetherian.fandom.com/wiki/Aetherian_Wiki"
authors="10ion, Pylons, Noah, Da_Dragon, Mikeadon, BadBird, Gamer, DJDARKWATERS, jointheprayerbro , KidOfCubes "
description='''
The Aetheria Mod is the mod from Cube Kid's books come to real minecraft
'''

[[dependencies.aetheria]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




